// <auto-generated />
using System;
using Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250707023830_RefactorOperationAndLegTypes")]
    partial class RefactorOperationAndLegTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Entity.ApiConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedKey1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedKey2")
                        .HasColumnType("text");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSuccessfulSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ApiConnections");
                });

            modelBuilder.Entity("Core.Domain.Entity.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sector")
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("85268ee3-9701-473d-9cee-f5710de42269"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "US Dollar",
                            Ticker = "USD"
                        },
                        new
                        {
                            Id = new Guid("a7df8de5-2fbb-4746-b957-cfe155b83ad0"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Euro",
                            Ticker = "EUR"
                        },
                        new
                        {
                            Id = new Guid("8e8041eb-2a40-4b5a-8859-925efcd97410"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Japanese Yen",
                            Ticker = "JPY"
                        },
                        new
                        {
                            Id = new Guid("c1633cef-f612-42e8-870a-9364413eea5f"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "British Pound Sterling",
                            Ticker = "GBP"
                        },
                        new
                        {
                            Id = new Guid("3a0b2c69-5c37-4fc4-b104-45dcd7c1bb0b"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Swiss Franc",
                            Ticker = "CHF"
                        },
                        new
                        {
                            Id = new Guid("628de140-d182-4621-8d31-cb467d2003e5"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Canadian Dollar",
                            Ticker = "CAD"
                        },
                        new
                        {
                            Id = new Guid("45af5a4b-d11c-4758-b7d9-523d37281773"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Australian Dollar",
                            Ticker = "AUD"
                        },
                        new
                        {
                            Id = new Guid("913e610b-ee6d-4181-b202-6bf281b9e284"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Chinese Yuan",
                            Ticker = "CNY"
                        },
                        new
                        {
                            Id = new Guid("c89647ac-cac1-42eb-831b-3b1143a84c84"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Hong Kong Dollar",
                            Ticker = "HKD"
                        },
                        new
                        {
                            Id = new Guid("9d0118d2-b19a-47cb-868e-b3e4bc49deb5"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Singapore Dollar",
                            Ticker = "SGD"
                        },
                        new
                        {
                            Id = new Guid("b1934c1a-9ebf-4a93-a319-32099930191b"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Norwegian Krone",
                            Ticker = "NOK"
                        },
                        new
                        {
                            Id = new Guid("6b6d7b91-5dc2-4c5d-9a53-0f3e0f869b94"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Swedish Krona",
                            Ticker = "SEK"
                        },
                        new
                        {
                            Id = new Guid("3696a040-2efa-4b33-9975-cf1d24c5aa16"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Danish Krone",
                            Ticker = "DKK"
                        },
                        new
                        {
                            Id = new Guid("75464266-69d7-4c9f-8f5d-68f0d04a772c"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Icelandic Krona",
                            Ticker = "ISK"
                        },
                        new
                        {
                            Id = new Guid("e5d1db03-4961-4b0a-9981-09205c145ce0"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Czech Koruna",
                            Ticker = "CZK"
                        },
                        new
                        {
                            Id = new Guid("b79c2d08-1af4-4768-bcd4-2c2e832acc9d"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Hungarian Forint",
                            Ticker = "HUF"
                        },
                        new
                        {
                            Id = new Guid("74fd7619-1182-4cc1-a016-56e1d9ab9974"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Polish Zloty",
                            Ticker = "PLN"
                        },
                        new
                        {
                            Id = new Guid("bd554dc8-122c-4c30-b6ae-e02497bde339"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Romanian Leu",
                            Ticker = "RON"
                        },
                        new
                        {
                            Id = new Guid("65bb4191-52ff-4c1d-ad87-b79e1ce2eca7"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Bulgarian Lev",
                            Ticker = "BGN"
                        },
                        new
                        {
                            Id = new Guid("e7966360-4380-41bb-a51e-d3985635e5d2"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Croatian Kuna",
                            Ticker = "HRK"
                        },
                        new
                        {
                            Id = new Guid("051a2dc8-be73-4ca5-8b9c-abf89c330e1d"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Serbian Dinar",
                            Ticker = "RSD"
                        },
                        new
                        {
                            Id = new Guid("190481d0-49c4-4874-b708-87050e968608"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Macedonian Denar",
                            Ticker = "MKD"
                        },
                        new
                        {
                            Id = new Guid("560bca24-a063-43c3-ac53-473633820ce6"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Albanian Lek",
                            Ticker = "ALL"
                        },
                        new
                        {
                            Id = new Guid("46b04247-7109-4cf4-8f84-521bd3e0e08c"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Bosnia and Herzegovina Convertible Mark",
                            Ticker = "BAM"
                        },
                        new
                        {
                            Id = new Guid("964c1f82-cfad-4a7e-84db-b72a67285f21"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Moldovan Leu",
                            Ticker = "MDL"
                        },
                        new
                        {
                            Id = new Guid("d0fb75d6-96f0-4510-8a4f-2ff680e7778c"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Ukrainian Hryvnia",
                            Ticker = "UAH"
                        },
                        new
                        {
                            Id = new Guid("c5c8eba9-e580-43ec-9b7b-3e8934c54e6e"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Belarusian Ruble",
                            Ticker = "BYN"
                        },
                        new
                        {
                            Id = new Guid("4052ae6c-da65-435b-b808-f5edef965c50"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Russian Ruble",
                            Ticker = "RUB"
                        },
                        new
                        {
                            Id = new Guid("6c54ee8c-6af1-4e1f-bfeb-7898cd39de99"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Turkish Lira",
                            Ticker = "TRY"
                        },
                        new
                        {
                            Id = new Guid("a4514e8c-e00b-4d59-aa89-86eebb3d33d3"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Georgian Lari",
                            Ticker = "GEL"
                        },
                        new
                        {
                            Id = new Guid("4d1f12b3-df31-40b4-84f2-1784956a3af9"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Armenian Dram",
                            Ticker = "AMD"
                        },
                        new
                        {
                            Id = new Guid("60a959de-eab6-49db-90ed-10ec0970f944"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Azerbaijani Manat",
                            Ticker = "AZN"
                        },
                        new
                        {
                            Id = new Guid("54e59f4e-649d-46fe-8904-0f18ce017c4a"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Indian Rupee",
                            Ticker = "INR"
                        },
                        new
                        {
                            Id = new Guid("3f2b3bc5-2f85-4593-abef-56038358305e"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "South Korean Won",
                            Ticker = "KRW"
                        },
                        new
                        {
                            Id = new Guid("29ce6769-6bf9-4922-ac58-3ad21cc0a3c4"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Indonesian Rupiah",
                            Ticker = "IDR"
                        },
                        new
                        {
                            Id = new Guid("104cf31a-7608-4183-b336-448851de2c20"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Malaysian Ringgit",
                            Ticker = "MYR"
                        },
                        new
                        {
                            Id = new Guid("0ac2b441-37ca-4763-aaec-c42f48e2714d"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Thai Baht",
                            Ticker = "THB"
                        },
                        new
                        {
                            Id = new Guid("c6a1e175-611b-4ef7-9ce3-5ccdabc272b8"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Philippine Peso",
                            Ticker = "PHP"
                        },
                        new
                        {
                            Id = new Guid("cb1c4b81-4e8e-473d-9c8e-b7aa4cb97542"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Vietnamese Dong",
                            Ticker = "VND"
                        },
                        new
                        {
                            Id = new Guid("73fabb4b-df49-4697-8f78-a275480c95cc"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Taiwan Dollar",
                            Ticker = "TWD"
                        },
                        new
                        {
                            Id = new Guid("3553faec-0c2a-441b-a01e-8ce54e6042d0"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Cambodian Riel",
                            Ticker = "KHR"
                        },
                        new
                        {
                            Id = new Guid("35aba6c3-b9bc-4198-a8ea-9b77a04797da"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Lao Kip",
                            Ticker = "LAK"
                        },
                        new
                        {
                            Id = new Guid("c17debd5-21e9-469d-ab53-03c03693a1c3"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Myanmar Kyat",
                            Ticker = "MMK"
                        },
                        new
                        {
                            Id = new Guid("a59f4255-8a85-4eb2-8f4e-881359fc0cf4"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Bangladeshi Taka",
                            Ticker = "BDT"
                        },
                        new
                        {
                            Id = new Guid("eb72b39e-2038-413d-bf6e-cddacfd3a8ac"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Pakistani Rupee",
                            Ticker = "PKR"
                        },
                        new
                        {
                            Id = new Guid("34563c3f-a91e-49b4-b3af-37a58c93f452"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Sri Lankan Rupee",
                            Ticker = "LKR"
                        },
                        new
                        {
                            Id = new Guid("705ed296-9f28-4e1a-b28d-49921524bd16"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Nepalese Rupee",
                            Ticker = "NPR"
                        },
                        new
                        {
                            Id = new Guid("33638d97-d492-4d21-8090-0f17fcf7618b"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Bhutanese Ngultrum",
                            Ticker = "BTN"
                        },
                        new
                        {
                            Id = new Guid("93386720-dcad-4d59-9025-d3ecf09c71a6"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Maldivian Rufiyaa",
                            Ticker = "MVR"
                        },
                        new
                        {
                            Id = new Guid("5127a26d-c355-4530-9ecd-a89b67fd4522"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Afghan Afghani",
                            Ticker = "AFN"
                        },
                        new
                        {
                            Id = new Guid("af3a1dcc-36e4-4a0e-937c-16f10dfd89b4"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Kazakhstani Tenge",
                            Ticker = "KZT"
                        },
                        new
                        {
                            Id = new Guid("cbcf9772-59c7-4c89-99a9-2b791ca376c9"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Kyrgyzstani Som",
                            Ticker = "KGS"
                        },
                        new
                        {
                            Id = new Guid("43fb8d35-e60a-4249-b330-f58f6589bf49"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Tajikistani Somoni",
                            Ticker = "TJS"
                        },
                        new
                        {
                            Id = new Guid("bb9e380e-fabf-4fca-82b1-f9df140ca702"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Turkmenistani Manat",
                            Ticker = "TMT"
                        },
                        new
                        {
                            Id = new Guid("ca7aef06-e664-4012-ad1c-cacc10bdda11"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Uzbekistani Som",
                            Ticker = "UZS"
                        },
                        new
                        {
                            Id = new Guid("babade4b-64b5-4083-b0ec-a90d6a27886c"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Mongolian Tugrik",
                            Ticker = "MNT"
                        },
                        new
                        {
                            Id = new Guid("4ad2f770-cd8a-44ab-8f9f-4a3d1efd5586"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "North Korean Won",
                            Ticker = "KPW"
                        },
                        new
                        {
                            Id = new Guid("ab47e1e4-88f5-4946-9ee7-51bce572d1b7"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Brunei Dollar",
                            Ticker = "BND"
                        },
                        new
                        {
                            Id = new Guid("100b0b5d-f9f9-427e-b6ce-9490f751ed00"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Macanese Pataca",
                            Ticker = "MOP"
                        },
                        new
                        {
                            Id = new Guid("a7bcaa45-86e1-41ab-8b55-73da45d1ddfa"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Saudi Riyal",
                            Ticker = "SAR"
                        },
                        new
                        {
                            Id = new Guid("702af8bc-81c5-4982-89f5-20eb73c996c2"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "UAE Dirham",
                            Ticker = "AED"
                        },
                        new
                        {
                            Id = new Guid("dd9b7f44-84d1-4d7c-aaf1-613266ac23d0"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Qatari Riyal",
                            Ticker = "QAR"
                        },
                        new
                        {
                            Id = new Guid("1e39ab48-e189-43f9-b33c-057bdadb5213"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Kuwaiti Dinar",
                            Ticker = "KWD"
                        },
                        new
                        {
                            Id = new Guid("4e31bb57-33ca-47ce-a114-0709cb8563b5"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Bahraini Dinar",
                            Ticker = "BHD"
                        },
                        new
                        {
                            Id = new Guid("322ac18b-bf6f-40fe-9190-139b7d4de83a"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Omani Rial",
                            Ticker = "OMR"
                        },
                        new
                        {
                            Id = new Guid("953dd944-6505-4f9b-9b47-3b2ca92e80dc"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Israeli New Shekel",
                            Ticker = "ILS"
                        },
                        new
                        {
                            Id = new Guid("1ad046d8-6229-45a7-8eab-b5f726c5c588"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Jordanian Dinar",
                            Ticker = "JOD"
                        },
                        new
                        {
                            Id = new Guid("2a092769-62f9-4dca-86a2-59d3d2953d4d"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Lebanese Pound",
                            Ticker = "LBP"
                        },
                        new
                        {
                            Id = new Guid("f9bc65d5-f368-46fc-8be7-50289a7c6aaf"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Syrian Pound",
                            Ticker = "SYP"
                        },
                        new
                        {
                            Id = new Guid("addd50a0-ecf3-4abd-ab68-365f342dd20e"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Iraqi Dinar",
                            Ticker = "IQD"
                        },
                        new
                        {
                            Id = new Guid("aa9801cf-001f-4bbb-8a3f-f9ff0303a2a6"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Iranian Rial",
                            Ticker = "IRR"
                        },
                        new
                        {
                            Id = new Guid("6b35e375-0bf3-4388-a24a-953e82b9a296"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Yemeni Rial",
                            Ticker = "YER"
                        },
                        new
                        {
                            Id = new Guid("a586da22-e5a9-4598-9b59-42014b4cd8fa"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "South African Rand",
                            Ticker = "ZAR"
                        },
                        new
                        {
                            Id = new Guid("b14e6254-c8f2-458b-9f88-01a23e581634"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Egyptian Pound",
                            Ticker = "EGP"
                        },
                        new
                        {
                            Id = new Guid("d43cb3b5-8ace-4b7f-92c9-af9da9d91ee5"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Moroccan Dirham",
                            Ticker = "MAD"
                        },
                        new
                        {
                            Id = new Guid("92de6f4f-2d85-4469-a186-164fea162980"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Tunisian Dinar",
                            Ticker = "TND"
                        },
                        new
                        {
                            Id = new Guid("763e302d-3954-4792-bfc3-827db5fdbd65"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Algerian Dinar",
                            Ticker = "DZD"
                        },
                        new
                        {
                            Id = new Guid("ed3d69e7-b4a6-429a-a5e8-0e74538603bf"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Libyan Dinar",
                            Ticker = "LYD"
                        },
                        new
                        {
                            Id = new Guid("cf28b256-9301-4c92-8410-c7335c7c92d8"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Sudanese Pound",
                            Ticker = "SDG"
                        },
                        new
                        {
                            Id = new Guid("fc10ef50-49f4-41ed-ab1f-06db14675969"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "South Sudanese Pound",
                            Ticker = "SSP"
                        },
                        new
                        {
                            Id = new Guid("04133db8-dac2-49b5-b1c6-e01498e55dab"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Ethiopian Birr",
                            Ticker = "ETB"
                        },
                        new
                        {
                            Id = new Guid("5bee2db3-1b18-4694-b5f0-459a87a6097c"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Eritrean Nakfa",
                            Ticker = "ERN"
                        },
                        new
                        {
                            Id = new Guid("63febbff-3242-4874-9c65-ccba0a1d873d"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Djiboutian Franc",
                            Ticker = "DJF"
                        },
                        new
                        {
                            Id = new Guid("a7371f04-e9d1-4762-940b-9aa680471f90"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Somali Shilling",
                            Ticker = "SOS"
                        },
                        new
                        {
                            Id = new Guid("a669b9e9-9a15-4da4-8abf-899264f477e7"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Kenyan Shilling",
                            Ticker = "KES"
                        },
                        new
                        {
                            Id = new Guid("3d43f193-d370-43ed-9d53-1199214c8e43"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Ugandan Shilling",
                            Ticker = "UGX"
                        },
                        new
                        {
                            Id = new Guid("6e47ac3b-258e-4326-9fe7-632ccd04fa32"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Tanzanian Shilling",
                            Ticker = "TZS"
                        },
                        new
                        {
                            Id = new Guid("eca9bbd3-5240-4b4c-8575-f3a59c947b24"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Rwandan Franc",
                            Ticker = "RWF"
                        },
                        new
                        {
                            Id = new Guid("9156298b-7a49-499b-97ae-1819fd0a489e"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Burundian Franc",
                            Ticker = "BIF"
                        },
                        new
                        {
                            Id = new Guid("18ac3af6-a364-423c-88ed-5c97e9ebaa47"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Malagasy Ariary",
                            Ticker = "MGA"
                        },
                        new
                        {
                            Id = new Guid("bc9a5895-5cd5-4079-9670-92697463b441"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Mauritian Rupee",
                            Ticker = "MUR"
                        },
                        new
                        {
                            Id = new Guid("92dd6c84-1cb3-40b0-9707-73e5d6063475"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Seychellois Rupee",
                            Ticker = "SCR"
                        },
                        new
                        {
                            Id = new Guid("0be14c9b-c1b5-482e-bd34-88dd1fa04470"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Comorian Franc",
                            Ticker = "KMF"
                        },
                        new
                        {
                            Id = new Guid("40e5a52b-01bd-4264-a05c-9b3e59f2e989"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Angolan Kwanza",
                            Ticker = "AOA"
                        },
                        new
                        {
                            Id = new Guid("016853d1-a20d-40d9-89b0-8f9223d817dc"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Mozambican Metical",
                            Ticker = "MZN"
                        },
                        new
                        {
                            Id = new Guid("011bf9f2-19ac-4e0f-8ab0-7ae450011d39"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Zambian Kwacha",
                            Ticker = "ZMW"
                        },
                        new
                        {
                            Id = new Guid("a14c3f63-562b-41b9-8abd-4d88bc69a941"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Zimbabwean Dollar",
                            Ticker = "ZWL"
                        },
                        new
                        {
                            Id = new Guid("20531207-647d-418a-b73c-70cff4b02863"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Botswana Pula",
                            Ticker = "BWP"
                        },
                        new
                        {
                            Id = new Guid("14f8a913-391c-4eb9-8b3f-d9ff79419922"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Swazi Lilangeni",
                            Ticker = "SZL"
                        },
                        new
                        {
                            Id = new Guid("0757324f-a547-4cfa-8f51-076ec2cd46bf"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Lesotho Loti",
                            Ticker = "LSL"
                        },
                        new
                        {
                            Id = new Guid("fc95bb8e-2778-44bd-a504-867520074984"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Namibian Dollar",
                            Ticker = "NAD"
                        },
                        new
                        {
                            Id = new Guid("d865854f-20d5-486f-ac7d-a8e8a42cb753"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Gambian Dalasi",
                            Ticker = "GMD"
                        },
                        new
                        {
                            Id = new Guid("7821c62c-8206-4a57-85ce-ed93070578f9"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Guinean Franc",
                            Ticker = "GNF"
                        },
                        new
                        {
                            Id = new Guid("35d63400-d1cd-4c00-adc9-0d64d396e534"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Sierra Leonean Leone",
                            Ticker = "SLE"
                        },
                        new
                        {
                            Id = new Guid("948194e7-e4ed-4c7c-bc7e-249c496d4c59"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Liberian Dollar",
                            Ticker = "LRD"
                        },
                        new
                        {
                            Id = new Guid("039fe71b-dc81-4410-9491-52dd39481b9c"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Ghanaian Cedi",
                            Ticker = "GHS"
                        },
                        new
                        {
                            Id = new Guid("c934342b-c38a-4751-bd7d-c0f4368c10c3"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Nigerian Naira",
                            Ticker = "NGN"
                        },
                        new
                        {
                            Id = new Guid("84eacc01-54ad-40ba-b18d-2467d4181815"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "West African CFA Franc",
                            Ticker = "XOF"
                        },
                        new
                        {
                            Id = new Guid("f40f635a-327b-4f7c-8468-594190e6c824"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Central African CFA Franc",
                            Ticker = "XAF"
                        },
                        new
                        {
                            Id = new Guid("1bec1473-f447-4e6b-ba7d-c1900863efa5"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Cape Verdean Escudo",
                            Ticker = "CVE"
                        },
                        new
                        {
                            Id = new Guid("a2dcbcbe-ff34-48e3-8160-8c7966d70ad7"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "São Tomé and Príncipe Dobra",
                            Ticker = "STN"
                        },
                        new
                        {
                            Id = new Guid("664e5334-e253-4c43-96d7-0785ccd56960"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Congolese Franc",
                            Ticker = "CDF"
                        },
                        new
                        {
                            Id = new Guid("b149f3de-a94f-4120-8dda-fe7083d48c9c"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Central African Republic Franc",
                            Ticker = "CAF"
                        },
                        new
                        {
                            Id = new Guid("5714346e-efde-4eea-9b9d-14c0267b75ce"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "CFP Franc",
                            Ticker = "XPF"
                        },
                        new
                        {
                            Id = new Guid("b7528203-349a-464a-a868-4b5abdaa2611"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Malawian Kwacha",
                            Ticker = "MWK"
                        },
                        new
                        {
                            Id = new Guid("7c508994-8a32-4532-a296-31f7d40a07d4"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Brazilian Real",
                            Ticker = "BRL"
                        },
                        new
                        {
                            Id = new Guid("942b72ad-972e-4e9d-860c-ef01e244042f"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Argentine Peso",
                            Ticker = "ARS"
                        },
                        new
                        {
                            Id = new Guid("a93bb478-1d6d-4719-af30-a143173c2ec2"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Chilean Peso",
                            Ticker = "CLP"
                        },
                        new
                        {
                            Id = new Guid("f7608b63-5379-4a27-9a4a-9cb439f0c6bf"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Colombian Peso",
                            Ticker = "COP"
                        },
                        new
                        {
                            Id = new Guid("40571b4f-291f-408f-b93b-3ecdc2e72ea3"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Peruvian Sol",
                            Ticker = "PEN"
                        },
                        new
                        {
                            Id = new Guid("b0445410-3edc-4cc7-890b-fb3076047f8d"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Uruguayan Peso",
                            Ticker = "UYU"
                        },
                        new
                        {
                            Id = new Guid("9a469ae0-5049-47b7-9b72-f91cdce34d4c"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Paraguayan Guarani",
                            Ticker = "PYG"
                        },
                        new
                        {
                            Id = new Guid("820c0378-6344-4fa6-b8fc-98b07161e413"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Bolivian Boliviano",
                            Ticker = "BOB"
                        },
                        new
                        {
                            Id = new Guid("ba0e5661-a1e7-4623-809c-094b43dc36e5"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Venezuelan Bolívar Soberano",
                            Ticker = "VES"
                        },
                        new
                        {
                            Id = new Guid("a89fea51-7879-4b59-8123-037523474ccf"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Guyanese Dollar",
                            Ticker = "GYD"
                        },
                        new
                        {
                            Id = new Guid("20f5ffa3-082a-467e-bdf9-e03e23b1d7f7"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Surinamese Dollar",
                            Ticker = "SRD"
                        },
                        new
                        {
                            Id = new Guid("0c0dbd88-5565-45e7-9281-c37fab543c12"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Mexican Peso",
                            Ticker = "MXN"
                        },
                        new
                        {
                            Id = new Guid("a665e754-e608-407e-b47c-94dcf212141f"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Guatemalan Quetzal",
                            Ticker = "GTQ"
                        },
                        new
                        {
                            Id = new Guid("90dc230a-8ca3-4080-81f5-460d2805a2a7"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Belize Dollar",
                            Ticker = "BZD"
                        },
                        new
                        {
                            Id = new Guid("a1caaa29-0b72-4e5d-ba0a-5c90ed5aa897"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Honduran Lempira",
                            Ticker = "HNL"
                        },
                        new
                        {
                            Id = new Guid("4ed3d4c2-9b5c-4a91-83a2-2bc6dde2b5c5"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Nicaraguan Córdoba",
                            Ticker = "NIO"
                        },
                        new
                        {
                            Id = new Guid("66f539b7-551c-44e3-bc0f-18d5bcbd3f4d"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Costa Rican Colón",
                            Ticker = "CRC"
                        },
                        new
                        {
                            Id = new Guid("e02a5a41-80b2-4ca8-8b79-9233fb090af1"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Panamanian Balboa",
                            Ticker = "PAB"
                        },
                        new
                        {
                            Id = new Guid("8eb74adf-024b-4aff-9219-b68fe330a710"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Cuban Peso",
                            Ticker = "CUP"
                        },
                        new
                        {
                            Id = new Guid("c968759e-0abd-420b-b926-6526e7685312"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Jamaican Dollar",
                            Ticker = "JMD"
                        },
                        new
                        {
                            Id = new Guid("42e6af7f-774d-46c7-a17b-54d2e9ea844c"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Haitian Gourde",
                            Ticker = "HTG"
                        },
                        new
                        {
                            Id = new Guid("0cc652b9-0848-4056-9f67-b045ae3dd704"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Dominican Peso",
                            Ticker = "DOP"
                        },
                        new
                        {
                            Id = new Guid("0ed1b0fc-27a3-4af7-b220-b02423122854"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Trinidad and Tobago Dollar",
                            Ticker = "TTD"
                        },
                        new
                        {
                            Id = new Guid("d309920e-3986-43d0-85dd-b9df5080c1a6"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Barbadian Dollar",
                            Ticker = "BBD"
                        },
                        new
                        {
                            Id = new Guid("61c59eb4-6e91-4057-9b87-dc8d3d6def2a"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "East Caribbean Dollar",
                            Ticker = "XCD"
                        },
                        new
                        {
                            Id = new Guid("4a0e927d-8a55-43a2-a2ca-bfcab9e2c5a8"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Aruban Florin",
                            Ticker = "AWG"
                        },
                        new
                        {
                            Id = new Guid("4f9df6ee-dccd-456d-885c-cbdb55af9dcc"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Netherlands Antillean Guilder",
                            Ticker = "ANG"
                        },
                        new
                        {
                            Id = new Guid("04425aa8-2b84-4068-8afc-fb8d4422bd64"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Cayman Islands Dollar",
                            Ticker = "KYD"
                        },
                        new
                        {
                            Id = new Guid("cd52c20b-773b-4187-baa5-dcb1d92746d6"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Bermudian Dollar",
                            Ticker = "BMD"
                        },
                        new
                        {
                            Id = new Guid("ccda8f84-3dcd-454b-a1db-d2ef253328ff"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Bahamian Dollar",
                            Ticker = "BSD"
                        },
                        new
                        {
                            Id = new Guid("163675aa-8a0d-4edd-9299-3ecfb18863b3"),
                            AssetClass = "Cash",
                            IsCustom = false,
                            Name = "Falkland Islands Pound",
                            Ticker = "FKP"
                        });
                });

            modelBuilder.Entity("Core.Domain.Entity.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawData")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceOperationId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("Source", "SourceOperationId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("Core.Domain.Entity.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Core.Domain.Entity.PortfolioApiConnection", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiConnectionId")
                        .HasColumnType("uuid");

                    b.HasKey("PortfolioId", "ApiConnectionId");

                    b.HasIndex("ApiConnectionId");

                    b.ToTable("PortfolioApiConnections");
                });

            modelBuilder.Entity("Core.Domain.Entity.PortfolioDailySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostBasis")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PortfolioDailySnapshots");
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CostBasisMethod")
                        .HasColumnType("integer");

                    b.Property<string>("JurisdictionCountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("TaxYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TaxReports");
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxReportPortfolio", b =>
                {
                    b.Property<Guid>("TaxReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.HasKey("TaxReportId", "PortfolioId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("TaxReportPortfolios");
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxableEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostBasis")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DateOfDisposal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HoldingPeriod")
                        .HasColumnType("integer");

                    b.Property<decimal>("Proceeds")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("QuantityDisposed")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<Guid>("SourceOperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaxReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("SourceOperationId");

                    b.HasIndex("TaxReportId");

                    b.ToTable("TaxableEvents");
                });

            modelBuilder.Entity("Core.Domain.Entity.TransactionLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PriceCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PricePerUnit")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("OperationId");

                    b.HasIndex("PriceCurrencyId");

                    b.ToTable("TransactionLegs");
                });

            modelBuilder.Entity("Core.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entity.Operation", b =>
                {
                    b.HasOne("Core.Domain.Entity.Portfolio", null)
                        .WithMany("Operations")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entity.Portfolio", b =>
                {
                    b.HasOne("Core.Domain.Entity.User", null)
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entity.PortfolioApiConnection", b =>
                {
                    b.HasOne("Core.Domain.Entity.ApiConnection", "ApiConnection")
                        .WithMany()
                        .HasForeignKey("ApiConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.Portfolio", "Portfolio")
                        .WithMany("ApiConnections")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiConnection");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxReport", b =>
                {
                    b.HasOne("Core.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxReportPortfolio", b =>
                {
                    b.HasOne("Core.Domain.Entity.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.TaxReport", null)
                        .WithMany("IncludedPortfolios")
                        .HasForeignKey("TaxReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxableEvent", b =>
                {
                    b.HasOne("Core.Domain.Entity.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.Operation", null)
                        .WithMany()
                        .HasForeignKey("SourceOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.TaxReport", null)
                        .WithMany("TaxableEvents")
                        .HasForeignKey("TaxReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entity.TransactionLeg", b =>
                {
                    b.HasOne("Core.Domain.Entity.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.Operation", "Operation")
                        .WithMany("Legs")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.Asset", "PriceCurrency")
                        .WithMany()
                        .HasForeignKey("PriceCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("Operation");

                    b.Navigation("PriceCurrency");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Core.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Core.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Core.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entity.Operation", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("Core.Domain.Entity.Portfolio", b =>
                {
                    b.Navigation("ApiConnections");

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxReport", b =>
                {
                    b.Navigation("IncludedPortfolios");

                    b.Navigation("TaxableEvents");
                });

            modelBuilder.Entity("Core.Domain.Entity.User", b =>
                {
                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
