// <auto-generated />
using System;
using Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250704232912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Entity.ApiConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedKey1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedKey2")
                        .HasColumnType("text");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSuccessfulSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ApiConnections");
                });

            modelBuilder.Entity("Core.Domain.Entity.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetClass")
                        .HasColumnType("integer");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sector")
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2447cad-09cd-4d88-8ee6-fad1bf6439db"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "US Dollar",
                            Ticker = "USD"
                        },
                        new
                        {
                            Id = new Guid("61de6cb4-9b1a-45fd-a9bd-47a56617e718"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Euro",
                            Ticker = "EUR"
                        },
                        new
                        {
                            Id = new Guid("05e06868-8f76-4793-95e8-2c712cc0894a"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Japanese Yen",
                            Ticker = "JPY"
                        },
                        new
                        {
                            Id = new Guid("7be1726b-498d-4445-ac9f-a45fb2cac47e"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "British Pound Sterling",
                            Ticker = "GBP"
                        },
                        new
                        {
                            Id = new Guid("24a133df-c52c-48b9-ae6b-f912c3217c78"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Swiss Franc",
                            Ticker = "CHF"
                        },
                        new
                        {
                            Id = new Guid("4cee1848-ce24-4a1e-b984-b8e272059386"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Canadian Dollar",
                            Ticker = "CAD"
                        },
                        new
                        {
                            Id = new Guid("8fe8d78c-1659-4a13-a5e7-8e609d85e871"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Australian Dollar",
                            Ticker = "AUD"
                        },
                        new
                        {
                            Id = new Guid("663aed05-3efa-4e23-9add-acae97edfde7"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Chinese Yuan",
                            Ticker = "CNY"
                        },
                        new
                        {
                            Id = new Guid("0e3a43c3-ced3-44c9-8eff-92125f69f84e"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Hong Kong Dollar",
                            Ticker = "HKD"
                        },
                        new
                        {
                            Id = new Guid("108eb812-5056-47f4-bd4d-3e8795488ccd"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Singapore Dollar",
                            Ticker = "SGD"
                        },
                        new
                        {
                            Id = new Guid("2fa50609-3d49-415a-8165-cfb41dcdd5bc"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Norwegian Krone",
                            Ticker = "NOK"
                        },
                        new
                        {
                            Id = new Guid("a1f73f99-f262-413b-91c7-2b9434269fe7"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Swedish Krona",
                            Ticker = "SEK"
                        },
                        new
                        {
                            Id = new Guid("7dbd0cf4-88b5-4d63-9ace-c40b5457e17f"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Danish Krone",
                            Ticker = "DKK"
                        },
                        new
                        {
                            Id = new Guid("c9df998b-365a-45e1-a54d-cab06e00ce1f"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Icelandic Krona",
                            Ticker = "ISK"
                        },
                        new
                        {
                            Id = new Guid("647912a6-4d43-46c7-9b53-9888c005f4b6"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Czech Koruna",
                            Ticker = "CZK"
                        },
                        new
                        {
                            Id = new Guid("455b6463-ae97-4c8e-b76e-0e7fe6695be7"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Hungarian Forint",
                            Ticker = "HUF"
                        },
                        new
                        {
                            Id = new Guid("d1e9bb46-2643-4818-b47d-391cef92ffed"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Polish Zloty",
                            Ticker = "PLN"
                        },
                        new
                        {
                            Id = new Guid("026f86b5-3c88-4169-99d4-95850879e87a"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Romanian Leu",
                            Ticker = "RON"
                        },
                        new
                        {
                            Id = new Guid("2658e8c3-77a2-4462-b3a8-4527dd2ffc67"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Bulgarian Lev",
                            Ticker = "BGN"
                        },
                        new
                        {
                            Id = new Guid("7b171f95-97f2-4312-9a7b-3af40df2b0ad"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Croatian Kuna",
                            Ticker = "HRK"
                        },
                        new
                        {
                            Id = new Guid("55dc8d16-d3dd-4d64-86c0-ac1cee1d5fd9"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Serbian Dinar",
                            Ticker = "RSD"
                        },
                        new
                        {
                            Id = new Guid("d5e3b831-e600-4a7e-95eb-cbc87199a32b"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Macedonian Denar",
                            Ticker = "MKD"
                        },
                        new
                        {
                            Id = new Guid("7d5fbafc-964d-4088-be3a-45bc28161d06"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Albanian Lek",
                            Ticker = "ALL"
                        },
                        new
                        {
                            Id = new Guid("94e17a33-d71c-4b35-89bb-db2f5942d7c1"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Bosnia and Herzegovina Convertible Mark",
                            Ticker = "BAM"
                        },
                        new
                        {
                            Id = new Guid("5ff97503-b02f-4270-8969-a9dea0e0ccaf"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Moldovan Leu",
                            Ticker = "MDL"
                        },
                        new
                        {
                            Id = new Guid("39d35c6e-ad87-4b94-8d2f-ad603f1fbd8d"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Ukrainian Hryvnia",
                            Ticker = "UAH"
                        },
                        new
                        {
                            Id = new Guid("b6c97579-8d54-4883-9d8c-5060443ec822"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Belarusian Ruble",
                            Ticker = "BYN"
                        },
                        new
                        {
                            Id = new Guid("2d87129c-96fc-45bb-bfd6-a713ab996c23"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Russian Ruble",
                            Ticker = "RUB"
                        },
                        new
                        {
                            Id = new Guid("34c46ac5-fb63-4173-9959-ebd39118890f"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Turkish Lira",
                            Ticker = "TRY"
                        },
                        new
                        {
                            Id = new Guid("d0c9b454-2b6d-43bd-b1fb-1b23faeddc6f"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Georgian Lari",
                            Ticker = "GEL"
                        },
                        new
                        {
                            Id = new Guid("1dd71a42-4b2e-4b4c-b6ba-328c6d724473"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Armenian Dram",
                            Ticker = "AMD"
                        },
                        new
                        {
                            Id = new Guid("9d7b7e3e-865c-41c7-8e89-f293931064b1"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Azerbaijani Manat",
                            Ticker = "AZN"
                        },
                        new
                        {
                            Id = new Guid("c15412f6-7dec-43c8-ae41-79e83a9b118c"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Indian Rupee",
                            Ticker = "INR"
                        },
                        new
                        {
                            Id = new Guid("66c146e3-808d-4e5d-80aa-c44018cb50eb"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "South Korean Won",
                            Ticker = "KRW"
                        },
                        new
                        {
                            Id = new Guid("a5647e0e-4afe-4ab0-ba46-14a5946c4d43"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Indonesian Rupiah",
                            Ticker = "IDR"
                        },
                        new
                        {
                            Id = new Guid("9e962372-1faf-4058-a26d-b2650cb9f1ae"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Malaysian Ringgit",
                            Ticker = "MYR"
                        },
                        new
                        {
                            Id = new Guid("3b136058-452b-4964-abac-045bb7c9be42"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Thai Baht",
                            Ticker = "THB"
                        },
                        new
                        {
                            Id = new Guid("d1c48450-ed21-4672-8ebf-e67b27baf038"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Philippine Peso",
                            Ticker = "PHP"
                        },
                        new
                        {
                            Id = new Guid("82947a9e-85bd-4c13-a609-080ed08c29f6"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Vietnamese Dong",
                            Ticker = "VND"
                        },
                        new
                        {
                            Id = new Guid("71e7733a-9349-4c4f-91cd-dd8ac062b989"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Taiwan Dollar",
                            Ticker = "TWD"
                        },
                        new
                        {
                            Id = new Guid("b07afbf6-d542-45fb-9426-04fa7ec8b051"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Cambodian Riel",
                            Ticker = "KHR"
                        },
                        new
                        {
                            Id = new Guid("64143c05-c227-46bf-b4e9-b50e23dac42a"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Lao Kip",
                            Ticker = "LAK"
                        },
                        new
                        {
                            Id = new Guid("b7eb2fab-df0f-4d01-a59e-04375257610c"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Myanmar Kyat",
                            Ticker = "MMK"
                        },
                        new
                        {
                            Id = new Guid("184cfbd0-36c3-4796-b42f-51372a39fcab"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Bangladeshi Taka",
                            Ticker = "BDT"
                        },
                        new
                        {
                            Id = new Guid("d5a778db-61e5-4fc0-864c-0f3b45985afa"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Pakistani Rupee",
                            Ticker = "PKR"
                        },
                        new
                        {
                            Id = new Guid("2227b150-7379-4554-9e06-8b0a00829ec0"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Sri Lankan Rupee",
                            Ticker = "LKR"
                        },
                        new
                        {
                            Id = new Guid("a18aa9b9-42ed-4a33-9c6c-905b8c41f3e6"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Nepalese Rupee",
                            Ticker = "NPR"
                        },
                        new
                        {
                            Id = new Guid("2fdaea83-9f93-4e42-95d9-8a4a284541de"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Bhutanese Ngultrum",
                            Ticker = "BTN"
                        },
                        new
                        {
                            Id = new Guid("12a45ab9-0166-4195-94cb-d61ae5c646bc"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Maldivian Rufiyaa",
                            Ticker = "MVR"
                        },
                        new
                        {
                            Id = new Guid("07f88392-d02d-4879-9cf0-38bf7ee153f1"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Afghan Afghani",
                            Ticker = "AFN"
                        },
                        new
                        {
                            Id = new Guid("e4d2065d-9c41-4132-bf08-e992caa58ec4"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Kazakhstani Tenge",
                            Ticker = "KZT"
                        },
                        new
                        {
                            Id = new Guid("6a2d7d2a-8ee5-4682-aefe-f81089b81264"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Kyrgyzstani Som",
                            Ticker = "KGS"
                        },
                        new
                        {
                            Id = new Guid("4c99428e-15d2-4a26-814e-df0485fe2ba6"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Tajikistani Somoni",
                            Ticker = "TJS"
                        },
                        new
                        {
                            Id = new Guid("20a4575e-5819-4fad-ae8a-d91eaa9a005f"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Turkmenistani Manat",
                            Ticker = "TMT"
                        },
                        new
                        {
                            Id = new Guid("9c443b6d-a3e9-4a14-97e8-9844d907625a"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Uzbekistani Som",
                            Ticker = "UZS"
                        },
                        new
                        {
                            Id = new Guid("c22d2e2e-bf37-4cac-9b1c-f5571a559d97"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Mongolian Tugrik",
                            Ticker = "MNT"
                        },
                        new
                        {
                            Id = new Guid("b1a794ce-ad5f-4d7f-91a2-819b1dd5e756"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "North Korean Won",
                            Ticker = "KPW"
                        },
                        new
                        {
                            Id = new Guid("18bf8d2c-8c92-473e-a8fe-7db0691e2753"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Brunei Dollar",
                            Ticker = "BND"
                        },
                        new
                        {
                            Id = new Guid("0d8f3b42-976d-486b-bf2a-caa7b361174d"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Macanese Pataca",
                            Ticker = "MOP"
                        },
                        new
                        {
                            Id = new Guid("57e36279-d09f-4d46-8d51-aab67f5a8310"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Saudi Riyal",
                            Ticker = "SAR"
                        },
                        new
                        {
                            Id = new Guid("c88119b8-fa8f-4232-b970-377e155104a5"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "UAE Dirham",
                            Ticker = "AED"
                        },
                        new
                        {
                            Id = new Guid("814337ea-257e-4eff-9b70-77c6241c968e"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Qatari Riyal",
                            Ticker = "QAR"
                        },
                        new
                        {
                            Id = new Guid("2193cc16-f96b-414e-8bf9-d52899fd199e"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Kuwaiti Dinar",
                            Ticker = "KWD"
                        },
                        new
                        {
                            Id = new Guid("f7219f13-1120-4c81-b058-2ac8b09eb06a"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Bahraini Dinar",
                            Ticker = "BHD"
                        },
                        new
                        {
                            Id = new Guid("e9456e82-e049-4be6-8747-a68bc46382d0"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Omani Rial",
                            Ticker = "OMR"
                        },
                        new
                        {
                            Id = new Guid("c1142a11-84bf-4be5-b83c-2b3ee6e405d5"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Israeli New Shekel",
                            Ticker = "ILS"
                        },
                        new
                        {
                            Id = new Guid("f5e8f9b7-a142-4892-a71f-d8e3f8646d5f"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Jordanian Dinar",
                            Ticker = "JOD"
                        },
                        new
                        {
                            Id = new Guid("3f14e688-cf72-43d2-b4f5-7e264a3059f7"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Lebanese Pound",
                            Ticker = "LBP"
                        },
                        new
                        {
                            Id = new Guid("a788cbec-91b6-4926-9ce4-23829fb93c22"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Syrian Pound",
                            Ticker = "SYP"
                        },
                        new
                        {
                            Id = new Guid("12061183-c46c-4264-a26d-6089ed262931"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Iraqi Dinar",
                            Ticker = "IQD"
                        },
                        new
                        {
                            Id = new Guid("1997c794-2098-483c-87bf-c0b6272cc1de"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Iranian Rial",
                            Ticker = "IRR"
                        },
                        new
                        {
                            Id = new Guid("282e94e2-ecea-4af5-8ca8-b4aa510a9eb0"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Yemeni Rial",
                            Ticker = "YER"
                        },
                        new
                        {
                            Id = new Guid("c92098b2-ba07-4aff-8b7b-52a5c0518c3b"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "South African Rand",
                            Ticker = "ZAR"
                        },
                        new
                        {
                            Id = new Guid("b906a6c3-d805-428c-9f7e-9044a0c264b0"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Egyptian Pound",
                            Ticker = "EGP"
                        },
                        new
                        {
                            Id = new Guid("e4799e8d-87d5-4139-9686-5549c64be7b8"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Moroccan Dirham",
                            Ticker = "MAD"
                        },
                        new
                        {
                            Id = new Guid("53c24d9c-86a2-408c-aa49-ae078e9ab5fc"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Tunisian Dinar",
                            Ticker = "TND"
                        },
                        new
                        {
                            Id = new Guid("4eb6fd4a-5770-4d16-b4f1-dec85ded9455"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Algerian Dinar",
                            Ticker = "DZD"
                        },
                        new
                        {
                            Id = new Guid("7e29f768-a561-43f2-b142-31096247c127"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Libyan Dinar",
                            Ticker = "LYD"
                        },
                        new
                        {
                            Id = new Guid("85458e9d-d3fb-4324-8d5f-37ea3b35de79"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Sudanese Pound",
                            Ticker = "SDG"
                        },
                        new
                        {
                            Id = new Guid("342ab7b7-b682-4341-94c1-c98dd7a76aa4"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "South Sudanese Pound",
                            Ticker = "SSP"
                        },
                        new
                        {
                            Id = new Guid("cf37decf-2f5f-4f86-8a88-ee20a2b41150"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Ethiopian Birr",
                            Ticker = "ETB"
                        },
                        new
                        {
                            Id = new Guid("024f8c86-6909-48cd-8d73-c3e459d3179d"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Eritrean Nakfa",
                            Ticker = "ERN"
                        },
                        new
                        {
                            Id = new Guid("bc6b3a64-1729-4755-bf55-f912269c9a6f"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Djiboutian Franc",
                            Ticker = "DJF"
                        },
                        new
                        {
                            Id = new Guid("a930e6eb-2e00-4f07-b81d-e3cc93294bb5"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Somali Shilling",
                            Ticker = "SOS"
                        },
                        new
                        {
                            Id = new Guid("03a49e55-04e6-48bc-9a7c-a8f41962815c"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Kenyan Shilling",
                            Ticker = "KES"
                        },
                        new
                        {
                            Id = new Guid("34ada21d-ac91-428b-a22b-a45b304132fa"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Ugandan Shilling",
                            Ticker = "UGX"
                        },
                        new
                        {
                            Id = new Guid("f1fadfbe-51d5-49fb-85e0-504ae550bdd0"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Tanzanian Shilling",
                            Ticker = "TZS"
                        },
                        new
                        {
                            Id = new Guid("1ca7f042-fa02-4c69-8609-59ab3de4e87d"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Rwandan Franc",
                            Ticker = "RWF"
                        },
                        new
                        {
                            Id = new Guid("ddc37a97-9fe6-45dd-99be-601a9d59daa2"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Burundian Franc",
                            Ticker = "BIF"
                        },
                        new
                        {
                            Id = new Guid("9fb13e5a-df0b-40f5-b04f-c9007314131c"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Malagasy Ariary",
                            Ticker = "MGA"
                        },
                        new
                        {
                            Id = new Guid("25676d7f-2101-4485-bbd9-e9aa10fc13e5"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Mauritian Rupee",
                            Ticker = "MUR"
                        },
                        new
                        {
                            Id = new Guid("6c570f89-6b79-442b-87ce-6f08d38faae8"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Seychellois Rupee",
                            Ticker = "SCR"
                        },
                        new
                        {
                            Id = new Guid("14ecd1a3-fc23-459b-95fa-d96f256514f6"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Comorian Franc",
                            Ticker = "KMF"
                        },
                        new
                        {
                            Id = new Guid("5dbbbf94-0e92-4590-93c5-4505863ca5f2"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Angolan Kwanza",
                            Ticker = "AOA"
                        },
                        new
                        {
                            Id = new Guid("32b49394-032e-4039-b3fb-ec74e90e651e"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Mozambican Metical",
                            Ticker = "MZN"
                        },
                        new
                        {
                            Id = new Guid("330d6d95-bd76-4261-b45c-757be4c171d0"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Zambian Kwacha",
                            Ticker = "ZMW"
                        },
                        new
                        {
                            Id = new Guid("dcdd88a5-afc6-48da-9c18-3fe19a16b3a0"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Zimbabwean Dollar",
                            Ticker = "ZWL"
                        },
                        new
                        {
                            Id = new Guid("9dff6f64-147f-4d30-a16f-c8fd6e17c0e2"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Botswana Pula",
                            Ticker = "BWP"
                        },
                        new
                        {
                            Id = new Guid("e74a4a65-f4fb-45b4-a5e2-065eacd13961"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Swazi Lilangeni",
                            Ticker = "SZL"
                        },
                        new
                        {
                            Id = new Guid("c89e26f6-1910-4734-a225-b179f950b42f"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Lesotho Loti",
                            Ticker = "LSL"
                        },
                        new
                        {
                            Id = new Guid("1270444d-4246-489e-89af-cae50d2413b9"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Namibian Dollar",
                            Ticker = "NAD"
                        },
                        new
                        {
                            Id = new Guid("91afd8a5-2ebe-43bc-b2d0-f7305ece6942"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Gambian Dalasi",
                            Ticker = "GMD"
                        },
                        new
                        {
                            Id = new Guid("8039eeac-40fa-47cf-bb6b-3b80a8aaed1d"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Guinean Franc",
                            Ticker = "GNF"
                        },
                        new
                        {
                            Id = new Guid("33d43655-d8a7-494e-b45c-1a8c86b74cc4"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Sierra Leonean Leone",
                            Ticker = "SLE"
                        },
                        new
                        {
                            Id = new Guid("b0383f66-0007-496a-9d56-a668121a1310"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Liberian Dollar",
                            Ticker = "LRD"
                        },
                        new
                        {
                            Id = new Guid("334847cd-724e-4658-8651-ad317a79f032"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Ghanaian Cedi",
                            Ticker = "GHS"
                        },
                        new
                        {
                            Id = new Guid("accb3d3f-9427-4f5b-ad55-75cbe5377186"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Nigerian Naira",
                            Ticker = "NGN"
                        },
                        new
                        {
                            Id = new Guid("0dfdf499-d77d-414f-b124-a9f61cc43302"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "West African CFA Franc",
                            Ticker = "XOF"
                        },
                        new
                        {
                            Id = new Guid("6194b501-6c22-4f3f-ba76-1a8f5d1b7229"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Central African CFA Franc",
                            Ticker = "XAF"
                        },
                        new
                        {
                            Id = new Guid("c4140e31-efb7-49a2-94b4-9bcb999c2d7b"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Cape Verdean Escudo",
                            Ticker = "CVE"
                        },
                        new
                        {
                            Id = new Guid("d3d7342b-a4aa-4832-b082-bb95f1b3c9c1"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "São Tomé and Príncipe Dobra",
                            Ticker = "STN"
                        },
                        new
                        {
                            Id = new Guid("5a1f0ab5-2b7c-4ef4-a202-dab1c23036f0"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Congolese Franc",
                            Ticker = "CDF"
                        },
                        new
                        {
                            Id = new Guid("03c82b37-b491-4eda-94f9-cd674fdc9e4c"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Central African Republic Franc",
                            Ticker = "CAF"
                        },
                        new
                        {
                            Id = new Guid("51407e6b-b022-4743-a29a-6720956fa82e"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "CFP Franc",
                            Ticker = "XPF"
                        },
                        new
                        {
                            Id = new Guid("691b6fe9-d770-4df5-96f0-1c1ff4096467"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Malawian Kwacha",
                            Ticker = "MWK"
                        },
                        new
                        {
                            Id = new Guid("ca036578-a1a9-4449-8c11-3f0735f1ce96"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Brazilian Real",
                            Ticker = "BRL"
                        },
                        new
                        {
                            Id = new Guid("9fd52c0c-91e2-478b-9d2c-49bed0142057"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Argentine Peso",
                            Ticker = "ARS"
                        },
                        new
                        {
                            Id = new Guid("6e63c4ec-68df-44b9-bd5e-24c150470923"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Chilean Peso",
                            Ticker = "CLP"
                        },
                        new
                        {
                            Id = new Guid("49f1ec15-aab3-4b87-af58-ae2867b05582"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Colombian Peso",
                            Ticker = "COP"
                        },
                        new
                        {
                            Id = new Guid("d3cb4a85-0a91-4981-b460-9cd0b303821a"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Peruvian Sol",
                            Ticker = "PEN"
                        },
                        new
                        {
                            Id = new Guid("6b6321de-7fae-4a0f-97e6-30f4c29c969e"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Uruguayan Peso",
                            Ticker = "UYU"
                        },
                        new
                        {
                            Id = new Guid("199154c4-eb9e-4916-bd4c-f69025e1ad5e"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Paraguayan Guarani",
                            Ticker = "PYG"
                        },
                        new
                        {
                            Id = new Guid("c7e16a4e-bf28-4e1d-9b26-b59ae6ba596b"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Bolivian Boliviano",
                            Ticker = "BOB"
                        },
                        new
                        {
                            Id = new Guid("d1d9219b-d1e8-42e4-a9a4-3b1e6885890d"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Venezuelan Bolívar Soberano",
                            Ticker = "VES"
                        },
                        new
                        {
                            Id = new Guid("29201e8d-21f4-4757-8e3e-769734f488f2"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Guyanese Dollar",
                            Ticker = "GYD"
                        },
                        new
                        {
                            Id = new Guid("c88e8959-76e6-4bc6-a4ae-1cc4a49b2711"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Surinamese Dollar",
                            Ticker = "SRD"
                        },
                        new
                        {
                            Id = new Guid("8a05b642-daf9-491f-9069-57b0950d0255"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Mexican Peso",
                            Ticker = "MXN"
                        },
                        new
                        {
                            Id = new Guid("6a01b72f-8bdd-43a7-bdec-43165a8338f0"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Guatemalan Quetzal",
                            Ticker = "GTQ"
                        },
                        new
                        {
                            Id = new Guid("5d3ef524-0b65-4f94-bd5c-96a7752e44bf"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Belize Dollar",
                            Ticker = "BZD"
                        },
                        new
                        {
                            Id = new Guid("21e1ce6e-c52c-490c-9714-e45b156a1540"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Honduran Lempira",
                            Ticker = "HNL"
                        },
                        new
                        {
                            Id = new Guid("8f4a80c3-c44b-464c-abc2-a6b59acbd735"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Nicaraguan Córdoba",
                            Ticker = "NIO"
                        },
                        new
                        {
                            Id = new Guid("6469b582-f146-4e4e-8a70-0abe613ee07d"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Costa Rican Colón",
                            Ticker = "CRC"
                        },
                        new
                        {
                            Id = new Guid("12836d29-5bd7-44be-9899-ea5b62deafda"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Panamanian Balboa",
                            Ticker = "PAB"
                        },
                        new
                        {
                            Id = new Guid("85d3c698-3004-4698-b8d8-0791d8ffe16a"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Cuban Peso",
                            Ticker = "CUP"
                        },
                        new
                        {
                            Id = new Guid("be8b0477-748b-454b-9dee-4a03af13b079"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Jamaican Dollar",
                            Ticker = "JMD"
                        },
                        new
                        {
                            Id = new Guid("595ea6bb-b268-492f-a17d-2529f7480cca"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Haitian Gourde",
                            Ticker = "HTG"
                        },
                        new
                        {
                            Id = new Guid("4a8d05ff-e55f-4f4b-83ff-bd1eb087e155"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Dominican Peso",
                            Ticker = "DOP"
                        },
                        new
                        {
                            Id = new Guid("457838d7-4434-46c8-a407-8e2f1f7e844f"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Trinidad and Tobago Dollar",
                            Ticker = "TTD"
                        },
                        new
                        {
                            Id = new Guid("7a21fb6d-2d54-41e8-a71c-59d82a49b807"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Barbadian Dollar",
                            Ticker = "BBD"
                        },
                        new
                        {
                            Id = new Guid("2bb8b9a0-9c95-478e-9fc7-77ca07bf67a1"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "East Caribbean Dollar",
                            Ticker = "XCD"
                        },
                        new
                        {
                            Id = new Guid("c85bb462-c65b-4ebf-b348-f862f3cb4582"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Aruban Florin",
                            Ticker = "AWG"
                        },
                        new
                        {
                            Id = new Guid("9f99abf3-a0f1-438e-8bd4-6f4fe2e4b348"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Netherlands Antillean Guilder",
                            Ticker = "ANG"
                        },
                        new
                        {
                            Id = new Guid("946aea29-e85a-4405-8aff-326df580abdb"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Cayman Islands Dollar",
                            Ticker = "KYD"
                        },
                        new
                        {
                            Id = new Guid("53346a1b-ff62-42ba-948c-45f2a7f44bee"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Bermudian Dollar",
                            Ticker = "BMD"
                        },
                        new
                        {
                            Id = new Guid("e7a9a8f3-0bdb-45ba-a858-34b3bf79d305"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Bahamian Dollar",
                            Ticker = "BSD"
                        },
                        new
                        {
                            Id = new Guid("e4c5709d-1598-4aa5-997b-557934e63b7a"),
                            AssetClass = 4,
                            IsCustom = false,
                            Name = "Falkland Islands Pound",
                            Ticker = "FKP"
                        });
                });

            modelBuilder.Entity("Core.Domain.Entity.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawData")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceOperationId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("Source", "SourceOperationId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("Core.Domain.Entity.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Core.Domain.Entity.PortfolioApiConnection", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiConnectionId")
                        .HasColumnType("uuid");

                    b.HasKey("PortfolioId", "ApiConnectionId");

                    b.HasIndex("ApiConnectionId");

                    b.ToTable("PortfolioApiConnections");
                });

            modelBuilder.Entity("Core.Domain.Entity.PortfolioDailySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostBasis")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PortfolioDailySnapshots");
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CostBasisMethod")
                        .HasColumnType("integer");

                    b.Property<string>("JurisdictionCountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("TaxYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TaxReports");
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxReportPortfolio", b =>
                {
                    b.Property<Guid>("TaxReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.HasKey("TaxReportId", "PortfolioId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("TaxReportPortfolios");
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxableEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostBasis")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DateOfDisposal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HoldingPeriod")
                        .HasColumnType("integer");

                    b.Property<decimal>("Proceeds")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("QuantityDisposed")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<Guid>("SourceOperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaxReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("SourceOperationId");

                    b.HasIndex("TaxReportId");

                    b.ToTable("TaxableEvents");
                });

            modelBuilder.Entity("Core.Domain.Entity.TransactionLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PriceCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PricePerUnit")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("OperationId");

                    b.HasIndex("PriceCurrencyId");

                    b.ToTable("TransactionLegs");
                });

            modelBuilder.Entity("Core.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entity.Operation", b =>
                {
                    b.HasOne("Core.Domain.Entity.Portfolio", null)
                        .WithMany("Operations")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entity.Portfolio", b =>
                {
                    b.HasOne("Core.Domain.Entity.User", null)
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entity.PortfolioApiConnection", b =>
                {
                    b.HasOne("Core.Domain.Entity.ApiConnection", "ApiConnection")
                        .WithMany()
                        .HasForeignKey("ApiConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.Portfolio", "Portfolio")
                        .WithMany("ApiConnections")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiConnection");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxReport", b =>
                {
                    b.HasOne("Core.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxReportPortfolio", b =>
                {
                    b.HasOne("Core.Domain.Entity.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.TaxReport", null)
                        .WithMany("IncludedPortfolios")
                        .HasForeignKey("TaxReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxableEvent", b =>
                {
                    b.HasOne("Core.Domain.Entity.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.Operation", null)
                        .WithMany()
                        .HasForeignKey("SourceOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.TaxReport", null)
                        .WithMany("TaxableEvents")
                        .HasForeignKey("TaxReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entity.TransactionLeg", b =>
                {
                    b.HasOne("Core.Domain.Entity.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.Operation", null)
                        .WithMany("Legs")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.Asset", null)
                        .WithMany()
                        .HasForeignKey("PriceCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Core.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Core.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Core.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entity.Operation", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("Core.Domain.Entity.Portfolio", b =>
                {
                    b.Navigation("ApiConnections");

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("Core.Domain.Entity.TaxReport", b =>
                {
                    b.Navigation("IncludedPortfolios");

                    b.Navigation("TaxableEvents");
                });

            modelBuilder.Entity("Core.Domain.Entity.User", b =>
                {
                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
